// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-YVDWddSa_sYfZ1FdIvHC4fLBTkBUoIw',
    appId: '1:202704498184:web:9d44d959c6e2f1420a6bbd',
    messagingSenderId: '202704498184',
    projectId: 'e-bracket-62bb4',
    authDomain: 'e-bracket-62bb4.firebaseapp.com',
    storageBucket: 'e-bracket-62bb4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXRjGr7yduDySo5K4a_OgcK2PO30sNJUQ',
    appId: '1:202704498184:android:c0a8e498ed9f38810a6bbd',
    messagingSenderId: '202704498184',
    projectId: 'e-bracket-62bb4',
    storageBucket: 'e-bracket-62bb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUQMZZzM7naYFoXabbV1JBiV3WFFpeK7Y',
    appId: '1:202704498184:ios:b39f4f55e1c4967d0a6bbd',
    messagingSenderId: '202704498184',
    projectId: 'e-bracket-62bb4',
    storageBucket: 'e-bracket-62bb4.appspot.com',
    iosClientId: '202704498184-ib8d30da598936im28mudek959npck9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBracket',
  );
}
